# Generated by Django 4.2.16 on 2024-12-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='categoria',
            new_name='grado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_culminacion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_eleccion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='regimen',
        ),
    ]
