# Generated by Django 4.2.16 on 2024-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_rename_categoria_customuser_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='integrantes_fotos/'),
        ),
    ]
