# Generated by Django 4.2.16 on 2024-12-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_customuser_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTechnique',
            fields=[
                ('idtechnique', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description_default', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('idTopic', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description_default', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='edad',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('idsession', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicsRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.session')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.topic')),
            ],
            options={
                'unique_together': {('session', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='RecommendedTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=25, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.session')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.learningtechnique')),
            ],
            options={
                'unique_together': {('session', 'technique')},
            },
        ),
    ]
