# Generated by Django 4.2.16 on 2024-12-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0004_learningtechnique_topic_customuser_edad_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='edad',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remember_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Arequipa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Peru', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='Arequipa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(default='3ro sec', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Yeimy Huanca', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
