# Generated by Django 4.2.16 on 2024-12-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0006_alter_customuser_city_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsrequirement',
            name='state',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recommendedtechniques',
            name='user_agent',
            field=models.CharField(blank=True, default='agente', max_length=25, null=True),
        ),
    ]
