# Generated by Django 4.2.16 on 2024-12-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0007_topicsrequirement_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='nombre',
            field=models.CharField(default='Sesion <built-in function id>', max_length=255),
        ),
    ]
