# Generated by Django 4.2.16 on 2024-12-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesion', '0004_learningtechnique_topic_customuser_edad_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('idconversation', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesion.session')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTopicLearned',
            fields=[
                ('idknowledgelearned', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description_default', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubKnowledge',
            fields=[
                ('idsubknowledge', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description_default', models.TextField(blank=True, null=True)),
                ('knowledge_learned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companieroVirtual.knowledgetopiclearned')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idmessage', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=225)),
                ('date_hour', models.DateTimeField()),
                ('content', models.TextField()),
                ('new_knowledge', models.BooleanField()),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companieroVirtual.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companieroVirtual.message')),
                ('subknowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companieroVirtual.subknowledge')),
            ],
            options={
                'unique_together': {('subknowledge', 'message')},
            },
        ),
    ]
