# Generated by Django 4.2.16 on 2024-12-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companieroVirtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_hour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
